--[[
IRON CLASH - 3D arena fighter
Press Play (F5) to test. Use "Test > Clients and Servers" with 2 players to try PvP.
Stages are generated by ServerScriptService.IronClashServer.Modules.Arenas when the game starts.
Tuning lives in ReplicatedStorage.Shared.Config (damage, timer, CPU difficulty, sounds)
and ReplicatedStorage.Shared.Moves (frame data for every move).
]]
